---
  dt: 0.1

  #allow interpolation up to this many seconds
  interp_tol: 0.5

  #set to true to allow past target times to be filled by future data
  backward_interpolation: false

  data:
    - name: odom
      topic: /superodometry/integrated_to_init #namespaced in new bags
      type: OdomRBState
      args: {}

    - name: gps_odom
      topic: /odometry/filtered_odom
      type: OdomRBState
      args: {}

    - name: multisense_left_intrinsics
      topic: /multisense/left/image_rect_color/camera_info
      type: Intrinsics
      args: {}

    - name: image_left_color
      topic: /multisense/left/image_rect_color
      type: Image
      args: {}

    - name: pcl
      topic: /velodyne_1/velodyne_points
      type: PointCloud
      args: {}

    - name: super_odometry_pc
      topic: /superodometry/velodyne_cloud_registered #make sure this is in sensor_init and not sensor_init_rot
      type: PointCloud
      args: {}

    - name: local_navmap
      topic: /local_navmap
      type: BEVGrid
      args: {}

    - name: steer_angle
      topic: /talon/current_position
      type: Float32
      args: {}

    - name: goals
      topic: /next_waypoints/odom
      type: GoalArray
      args: {}