---
  main_topic: '/superodometry/velodyne_cloud_registered'
  dt: 0.1

  data:
    - name: odometry
      topic: /superodometry/integrated_to_init #namespaced in new bags
      type: OdomRBState
      args: {}

    - name: image_intrinsics
      topic: /multisense/left/image_rect_color/camera_info
      type: Intrinsics
      args: {}

    - name: image
      topic: /multisense/left/image_rect_color
      type: Image
      args: {}

    - name: pointcloud_in_odom
      topic: /superodometry/velodyne_cloud_registered #make sure this is in sensor_init and not sensor_init_rot
      type: PointCloud
      args: {}