---
dt: 0.1

#allow interpolation up to this many seconds
interp_tol: 0.2

#set to true to allow past target times to be filled by future data
backward_interpolation: false

#overrride tfs with values from config (STRONGLY RECOMMEND USING)
calib_file: $TARTANDRIVER_HOME/src/core/static_tf_publisher/config/offroad/yamaha.yaml

topics:
  # Odom
  - name: super_odometry
    topic: /superodometry/integrated_to_init #namespaced in new bags
    type: OdomRBState
    max_age: 1.

  - name: novatel_gps_odometry
    topic: /odometry/filtered_odom
    type: OdomRBState
    max_age: 1.

  - name: rtk_odometry
    topic: /rtk_gps/ekf/odometry_earth
    type: OdomRBState
    max_age: 1.
    optional: True

  # Proprio sensors
  - name: novatel_imu
    topic: /novatel/imu/data
    type: Imu
    max_age: 1.

  - name: pedal_pos
    topic: /racepak/pedal_pos
    type: PedalPos
    max_age: 1.
    optional: True

  - name: shock_pos
    topic: /racepak/shock_pos
    type: ShockPos
    max_age: 1.
    optional: True

  - name: wheel_rpm
    topic: /racepak/wheel_rpm
    type: WheelRPM
    max_age: 1.
    optional: True

  # Mapping
  # - name: pointcloud_in_odom
  #   topic: /superodometry/velodyne_cloud_registered #make sure this is in sensor_init and not sensor_init_rot
  #   type: PointCloud

  # Dynamics
  - name: steer_angle
    topic: /talon/current_position
    type: Float32
    max_age: 1.

  - name: target_steer_angle
    topic: /talon/steering_angle
    type: Float32
    max_age: 1.

  - name: mux_command
    topic: /mux/cmd
    type: Command
    max_age: 1.

  - name: teleop_command
    topic: /teleop_cmd
    type: Command
    max_age: 1.

  - name: auto_command
    topic: /auto_cmd
    type: Command
    max_age: 1.
    optional: True

  # Perception sensors
  # - name: image_intrinsics
  #   topic: /multisense/left/image_rect_color/camera_info
  #   type: Intrinsics
  #   max_age: 1.

  # - name: image
  #   topic: /multisense/left/image_rect_color
  #   type: Image
  #   max_age: 1.
