dt: 0.1
interp_tol: 0.2
backward_interpolation: false
topics:
  - name: odometry
    group: super_odometry
    topic: /integrated_to_init
    type: OdomRBState
    args: {}
  - name: pointcloud_in_odom
    group: super_odometry
    topic: /velodyne_cloud_registered_with_features
    type: PointCloud
    max_age: 1.0
    args: {}
  - name: multisense_left_rect_color
    group: sensors
    topic: /multisense/left/image_rect_color
    type: Image
    args: {}
  - name: roughness
    group: traversability
    topic: /traversability_cost
    type: Float32
    args: {}
