---
  dt: 0.1

  #allow interpolation up to this many seconds
  interp_tol: 0.2

  #set to true to allow past target times to be filled by future data
  backward_interpolation: false

  calibration: !include $TARTANDRIVER_HOME/src/core/static_tf_publisher/config/offroad/yamaha.yaml

  topics: !listcat
    - !include $TARTANDRIVER_HOME/src/core/ros_torch_converter/config/topics/yamaha/multisense_topics.yaml
    - !include $TARTANDRIVER_HOME/src/core/ros_torch_converter/config/topics/yamaha/super_odometry_topics.yaml
    - !include $TARTANDRIVER_HOME/src/core/ros_torch_converter/config/topics/yamaha/novatel_topics.yaml

    -
      - name: image_left_rect
        group: sensors
        topic: /multisense/left/image_rect
        type: Image
        max_age: 1.
        args: {}

      - name: image_right_rect
        group: sensors
        topic: /multisense/right/image_rect
        type: Image
        max_age: 1.
        args: {}

      - name: thermal_left
        group: sensors
        topic: /thermal_left/image
        type: Thermal16bitImage
        max_age: 1.
        args: {}

      - name: thermal_right
        group: sensors
        topic: /thermal_right/image
        type: Thermal16bitImage
        max_age: 1.
        args: {}

      - name: thermal_left_processed
        group: sensors
        topic: /thermal_left/image_processed
        type: ThermalImage
        max_age: 1.
        args: {}

      - name: thermal_right_processed
        group: sensors
        topic: /thermal_right/image_processed
        type: ThermalImage
        max_age: 1.
        args: {}

      - name: thermal_left_ffc
        group: sensors
        topic: /thermal_left/ffc_status
        type: FFCStatus
        max_age: 1.
        args: {}

      - name: thermal_right_ffc
        group: sensors
        topic: /thermal_right/ffc_status
        type: FFCStatus
        max_age: 1.
        args: {}
