---
  dt: 0.1

  #allow interpolation up to this many seconds
  interp_tol: 0.5

  #set to true to allow past target times to be filled by future data
  backward_interpolation: false

  data:
    - name: odom
      topic: /superodometry/integrated_to_init #namespaced in new bags
      type: OdomRBState
      args: {}

    - name: gps_odom
      topic: /odometry/filtered_odom
      type: OdomRBState
      args: {}

    - name: image_left_color_multisense
      topic: /multisense/left/image_rect_color
      type: Image
      args: {}

    - name: image_left_color
      topic: /thermal_right/image_processed
      type: ThermalImage
      args: {}

    - name: super_odometry_pc
      topic: /superodometry/velodyne_cloud_registered
      type: PointCloud
      args: {}

    - name: steer_angle
      topic: /talon/current_position
      type: Float32
      args: {}
