---
dt: 0.4 # match the rate in just_voxel_mapping_dtc.yaml (1/0.4 = 2.5 Hz)
interp_tol: 0.5
backward_interpolation: false

topics:
  - name: odometry
    topic: /spot2/base/autonomy/slam/aft_mapped_to_init
    type: OdomRBState
    max_age: 1.0
    args: {}

  - name: pointcloud_in_odom
    topic: /spot2/base/autonomy/slam/registered_scan
    type: PointCloud
    max_age: 1.0
    args: {}