dt: 0.1
interp_tol: 0.2
backward_interpolation: false
topics:
  - name: odometry
    group: super_odometry
    topic: /superodometry/integrated_to_init
    type: OdomRBState
    args: {}
  - name: pointcloud_in_odom
    group: super_odometry
    topic: /superodometry/velodyne_cloud_registered
    type: PointCloud
    max_age: 1.0
    args: {}
  - name: roughness
    group: traversability
    topic: /traversability_cost
    type: Float32
    args: {}
