---
  dt: 0.1

  #allow interpolation up to this many seconds
  interp_tol: 0.5

  #set to true to allow past target times to be filled by future data
  backward_interpolation: false

  data:
    - name: odom
      topic: /superodometry/integrated_to_init #namespaced in new bags
      type: OdomRBState
      args: {}

    - name: gps_odom
      topic: /odometry/filtered_odom
      type: OdomRBState
      args: {}

    - name: image_left_color
      topic: /multisense/left/image_rect_color
      type: Image
      args: {}

    - name: pcl
      topic: /velodyne_1/velodyne_points
      type: PointCloud
      args: {}

    - name: thermal_left
      topic: /thermal_left/image
      type: Thermal16bitImage
      args: {}
    
    - name: thermal_right
      topic: /thermal_right/image
      type: Thermal16bitImage
      args: {}
    
    - name: thermal_left_processed
      topic: /thermal_left/image_processed
      type: ThermalImage
      args: {}
    
    - name: thermal_right_processed
      topic: /thermal_right/image_processed
      type: ThermalImage
      args: {}
