---
  dt: 0.1

  #allow interpolation up to this many seconds
  interp_tol: 0.5

  #set to true to allow past target times to be filled by future data
  backward_interpolation: false

  data:
    - name: gps_odom
      topic: /zed/map_frame_odom
      type: OdomRBState
      args: {}

    - name: image
      topic: /zed/microstrain_inertial_driver/rgb/image_rect_color
      type: Image
      args: {}

    - name: dino_map
      topic: /dino_gridmap
      type: BEVGrid
      args: {}

    - name: costmap
      topic: /cherie_costmap
      type: BEVGrid
      args: {}

    - name: goals
      topic: /odom_waypoints
      type: GoalArray
      args: {}