- name: steer_angle
  group: controls
  topic: /talon/current_position
  type: Float32
  args: {}

- name: command
  group: controls
  topic: /mux/cmd
  type: Command
  args: {}

- name: teleop_command
  group: controls
  topic: /teleop_cmd
  type: Command
  args: {}

- name: auto_command
  group: controls
  topic: /auto_cmd
  type: Command
  args: {}