- name: intervention
  group: autonomy
  topic: /mux/intervention
  type: Bool
  max_age: 1.
  optional: true
  args: {}

- name: mppi_solution
  group: autonomy
  topic: /mppi/solution
  type: MPPISolution
  max_age: 1.
  optional: true
  args: {}

- name: track_path
  group: autonomy
  topic: /track_path
  type: Path
  max_age: 1.
  optional: true
  args: {}

- name: track_path_full
  group: autonomy
  topic: /track_path_full
  type: Path
  max_age: 1.
  optional: true
  args: {}

- name: waypoints
  topic: /next_waypoints/odom
  type: GoalArray
  group: autonomy
  max_age: 1000000000000000.
  optional: true
  args: {}