- name: mppi_solution
  group: mpc
  topic: /mppi/solution
  type: MPPISolution
  max_age: 1.
  optional: true
  args: {}

- name: track_path
  group: mpc
  topic: /track_path
  type: Path
  max_age: 1.
  optional: true
  args: {}

- name: track_path_full
  group: mpc
  topic: /track_path_full
  type: Path
  max_age: 1.
  optional: true
  args: {}